algoritmo "MostrarNome"

var
// texto- caractere- string
// verdadeiro/falso-logico-boolean
// numero inteiro - inteiro- int
// numero decimal- real- float
nomeUsarario : caractere

inicio
// output- saída-telas, leds, respota por vez , som
// input - entrada
// l- line break- quebra de linha

// numeUsario <-"filipe"
escreva("digite seu nome:")
leia(numeUsario)
escreva("0i, ")
escreval("Bom dia")

fimalgoritmo
