algoritmo "mago"


var

inicio
// condicional , utiliza-se boolean- logico
// senao / else- não é obrigatorio
// operadores RELACIONAIS
// <MENOR QUE
// > MAIOR QUE
// <= MENOR OU IGUAL QUE
// >= MAIOR OU IGUAL QUE 
// =(<-) ATRIBUIÇÃO
// == COMPARAÇÃO SIMPLES ( COMPARAR CONTEUDO)
// === COMPARAÇÃO COMPLEXA / COMPLETA (COMPARAR E TIPO)
// != (NAO) NÃO IGUAL
se (verdadeiro) entao
    escreval("estou no se")
// senao
// escraval ("estou no senao")

fimalgoritmo

